/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mayatm;

import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class MainScreen extends DocGhiFile {
    private User UserLogin = null;
    /**
     * Creates new form Screen
     */

    public MainScreen() {
        initComponents();
    }

    public MainScreen(User UserLogin) {
        this.UserLogin = UserLogin;
        initComponents();
        setLocationRelativeTo(null);
        txtName.setText(""+UserLogin.getName());
        btnWithDraw.setBackground(Color.gray);
        btnWithDraw.setForeground(Color.white);
	btnChangePass.setBackground(Color.gray);
        btnChangePass.setForeground(Color.white); 
	btnGetInfo.setBackground(Color.gray);
        btnGetInfo.setForeground(Color.white);
	btnShowMoney.setBackground(Color.gray);
        btnShowMoney.setForeground(Color.white);
	btnTransfer.setBackground(Color.gray);
        btnTransfer.setForeground(Color.white);
	btnExit.setBackground(Color.gray);
        btnExit.setForeground(Color.white);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnWithDraw = new javax.swing.JButton();
        btnChangePass = new javax.swing.JButton();
        btnGetInfo = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        btnTransfer = new javax.swing.JButton();
        btnShowMoney = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Màn hình chính");

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        btnWithDraw.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnWithDraw.setForeground(new java.awt.Color(240, 240, 240));
        btnWithDraw.setText("Rút tiền");
        btnWithDraw.setBorder(new javax.swing.border.MatteBorder(null));
        btnWithDraw.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnWithDrawMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnWithDrawMouseExited(evt);
            }
        });
        btnWithDraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithDrawActionPerformed(evt);
            }
        });

        btnChangePass.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnChangePass.setForeground(new java.awt.Color(240, 240, 240));
        btnChangePass.setText("Đổi mật khẩu");
        btnChangePass.setBorder(new javax.swing.border.MatteBorder(null));
        btnChangePass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnChangePassMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnChangePassMouseExited(evt);
            }
        });
        btnChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangePassActionPerformed(evt);
            }
        });

        btnGetInfo.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnGetInfo.setForeground(new java.awt.Color(240, 240, 240));
        btnGetInfo.setText("Thông tin KH");
        btnGetInfo.setBorder(new javax.swing.border.MatteBorder(null));
        btnGetInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnGetInfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnGetInfoMouseExited(evt);
            }
        });
        btnGetInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetInfoActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnExit.setForeground(new java.awt.Color(240, 240, 240));
        btnExit.setText("Thoát");
        btnExit.setBorder(new javax.swing.border.MatteBorder(null));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnTransfer.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnTransfer.setForeground(new java.awt.Color(240, 240, 240));
        btnTransfer.setText("Chuyển tiền");
        btnTransfer.setBorder(new javax.swing.border.MatteBorder(null));
        btnTransfer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTransferMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTransferMouseExited(evt);
            }
        });
        btnTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferActionPerformed(evt);
            }
        });

        btnShowMoney.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnShowMoney.setForeground(new java.awt.Color(240, 240, 240));
        btnShowMoney.setText("Xem số dư");
        btnShowMoney.setBorder(new javax.swing.border.MatteBorder(null));
        btnShowMoney.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnShowMoneyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnShowMoneyMouseExited(evt);
            }
        });
        btnShowMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowMoneyActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Xin chào:");

        txtName.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtName.setForeground(new java.awt.Color(240, 240, 240));
        txtName.setText(".");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnWithDraw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnChangePass, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                    .addComponent(btnGetInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnExit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnShowMoney, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTransfer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnWithDraw, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(btnShowMoney, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTransfer, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(btnChangePass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnGetInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(81, 81, 81))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnWithDrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithDrawActionPerformed
        // TODO add your handling code here:
        WithDraw a = new WithDraw(UserLogin);
        a.setVisible(true); 
    }//GEN-LAST:event_btnWithDrawActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        Begin b = new Begin();
        b.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangePassActionPerformed
        // TODO add your handling code here:
        ChangePass a = new ChangePass(UserLogin);
        a.setVisible(true);
        
    }//GEN-LAST:event_btnChangePassActionPerformed

    private void btnTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferActionPerformed
        // TODO add your handling code here:
        Transfer a = new Transfer(UserLogin);
        a.setVisible(true);
    }//GEN-LAST:event_btnTransferActionPerformed

    private void btnGetInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetInfoActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Tên NH:"+ UserLogin.getBankName()
        +"\nChủ thẻ: " + UserLogin.getName()
        +"\nCMND: " + UserLogin.getCardNumber()
        +"\nUsername: " + UserLogin.getUserName()
        +"\nPassword: " + UserLogin.getPass()
        + "\nSố dư: " + UserLogin.getMoney() + " VND","Thông tin cá nhân",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnGetInfoActionPerformed

    private void btnShowMoneyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowMoneyActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this,"Số dư của bạn là: " + UserLogin.getMoney() + " VND",
                "Số dư",JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnShowMoneyActionPerformed

    private void btnWithDrawMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWithDrawMouseEntered
        // TODO add your handling code here:
        btnWithDraw.setBackground(Color.green);
        btnWithDraw.setForeground(Color.black);
    }//GEN-LAST:event_btnWithDrawMouseEntered

    private void btnWithDrawMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWithDrawMouseExited
        // TODO add your handling code here:
        btnWithDraw.setBackground(Color.gray);
        btnWithDraw.setForeground(Color.white);   
    }//GEN-LAST:event_btnWithDrawMouseExited

    private void btnChangePassMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangePassMouseEntered
        // TODO add your handling code here:
        btnChangePass.setBackground(Color.green);
        btnChangePass.setForeground(Color.black);
    }//GEN-LAST:event_btnChangePassMouseEntered

    private void btnChangePassMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnChangePassMouseExited
        // TODO add your handling code here:
        btnChangePass.setBackground(Color.gray);
        btnChangePass.setForeground(Color.white);   
    }//GEN-LAST:event_btnChangePassMouseExited

    private void btnGetInfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGetInfoMouseEntered
        // TODO add your handling code here:
        btnGetInfo.setBackground(Color.green);
        btnGetInfo.setForeground(Color.black);
    }//GEN-LAST:event_btnGetInfoMouseEntered

    private void btnGetInfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGetInfoMouseExited
        // TODO add your handling code here:
        btnGetInfo.setBackground(Color.gray);
        btnGetInfo.setForeground(Color.white);
    }//GEN-LAST:event_btnGetInfoMouseExited

    private void btnShowMoneyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowMoneyMouseEntered
        // TODO add your handling code here:
        btnShowMoney.setBackground(Color.green);
        btnShowMoney.setForeground(Color.black);
    }//GEN-LAST:event_btnShowMoneyMouseEntered

    private void btnShowMoneyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnShowMoneyMouseExited
        // TODO add your handling code here:
        btnShowMoney.setBackground(Color.gray);
        btnShowMoney.setForeground(Color.white);
    }//GEN-LAST:event_btnShowMoneyMouseExited

    private void btnTransferMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransferMouseEntered
        // TODO add your handling code here:
        btnTransfer.setBackground(Color.green);
        btnTransfer.setForeground(Color.black);
    }//GEN-LAST:event_btnTransferMouseEntered

    private void btnTransferMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTransferMouseExited
        // TODO add your handling code here:
        btnTransfer.setBackground(Color.gray);
        btnTransfer.setForeground(Color.white);
    }//GEN-LAST:event_btnTransferMouseExited

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        btnExit.setBackground(Color.green);
        btnExit.setForeground(Color.black);
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
        btnExit.setBackground(Color.gray);
        btnExit.setForeground(Color.white);
    }//GEN-LAST:event_btnExitMouseExited

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChangePass;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGetInfo;
    private javax.swing.JButton btnShowMoney;
    private javax.swing.JButton btnTransfer;
    private javax.swing.JButton btnWithDraw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtName;
    // End of variables declaration//GEN-END:variables
}
