/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mayatm;

import java.io.File;
import java.io.PrintStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Transfer extends DocGhiFile {
    private List<User> a = new ArrayList<>();
    private User UserLogin = null;
    /**
     * Creates new form MoneyTransferScreen
     */
    public Transfer() {
        initComponents();
        docFile(a);
    }
    public Transfer(User UserLogin) {
        initComponents();
        setLocationRelativeTo(null);
        this.UserLogin = UserLogin;
        lblCardNumber.setText(UserLogin.getCardNumber());
        docFile(a);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblCardNumber = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtCardNumber = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cbxBankName = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtMoney = new javax.swing.JTextField();
        btnTransfer = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chuyển tiền");

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setForeground(new java.awt.Color(240, 240, 240));

        btnExit.setBackground(new java.awt.Color(153, 0, 0));
        btnExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExit.setForeground(new java.awt.Color(240, 240, 240));
        btnExit.setText("Thoát");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(240, 240, 240));
        jLabel5.setText("Tên người nhận:");

        txtName.setEditable(false);
        txtName.setBackground(new java.awt.Color(153, 255, 204));
        txtName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNameMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Tài khoản nguồn:");

        lblCardNumber.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCardNumber.setForeground(new java.awt.Color(240, 240, 240));
        lblCardNumber.setText("jLabel2");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(240, 240, 240));
        jLabel2.setText("Tài khoản đích:");

        txtCardNumber.setBackground(new java.awt.Color(153, 255, 204));
        txtCardNumber.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(240, 240, 240));
        jLabel3.setText("Tên ngân hàng:");

        cbxBankName.setBackground(new java.awt.Color(153, 255, 204));
        cbxBankName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbxBankName.setForeground(new java.awt.Color(255, 0, 0));
        cbxBankName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn ngân hàng", "Vietcombank", "Agribank", "BIDV", "Techcombank", "MBbank", "ACB" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Số tiền:");

        txtMoney.setBackground(new java.awt.Color(153, 255, 204));
        txtMoney.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnTransfer.setBackground(new java.awt.Color(153, 0, 0));
        btnTransfer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTransfer.setForeground(new java.awt.Color(240, 240, 240));
        btnTransfer.setText("Chuyển tiền");
        btnTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("*Vui lòng nhập đúng tên ngân hàng và số tài khoản người nhận");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtName)
                            .addComponent(txtCardNumber)
                            .addComponent(cbxBankName, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblCardNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMoney, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(114, 114, 114))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblCardNumber))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbxBankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCardNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMoney, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTransfer)
                    .addComponent(btnExit))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private boolean check(){
        String str = cbxBankName.getSelectedItem().toString();        
        for(User x: a){
            if(txtCardNumber.getText().equals(x.getCardNumber())
                    && str.equals(x.getBankName()))
                return true;
        }
        return false;
    }
    private void btnTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferActionPerformed
        // TODO add your handling code here:
        System.out.println(Long.parseLong(txtMoney.getText()) + " " + UserLogin.getMoney()); 
        if(check()){
            int choice = JOptionPane.showConfirmDialog(this, "Xác nhận chuyển tiền ?","Xác nhận !",JOptionPane.YES_NO_OPTION);
                if(choice==JOptionPane.NO_OPTION){
                    return;
                }
            long money = Long.parseLong(txtMoney.getText());
            if(money<=UserLogin.getMoney()
                    && UserLogin.getMoney()>=0){
                UserLogin.setMoney((UserLogin.getMoney()-money));
                for(User x: a){
                    if(UserLogin.getCmnd().equals(x.getCmnd())){
                        x.setMoney(x.getMoney()-money);
                        System.out.println("Bạn còn:" + x.getMoney());                        
                    }
                    if(txtCardNumber.getText().equals(x.getCardNumber())){
                        x.setMoney(x.getMoney()+money);
                    }
                    ghiFile(a);
                }
                int choice1 = JOptionPane.showConfirmDialog(this, "Bạn muốn in hoá đơn không ?","In hoá đơn ?",JOptionPane.YES_NO_OPTION);
                if(choice1==JOptionPane.NO_OPTION){
                    JOptionPane.showMessageDialog(this, "Chuyển tiền thành công!","Đã chuyển !",JOptionPane.INFORMATION_MESSAGE);
                    return;
                } else
                JOptionPane.showMessageDialog(this, "Tên người nhận: "+txtName.getText() +
                        "\nSố tài khoản người nhận: " + txtCardNumber.getText() + 
                        "\nSố tiền: " + txtMoney.getText() + " VND" +
                        "\nNgày giao dịch: " + java.time.LocalDateTime.now(), "Hoá đơn",JOptionPane.INFORMATION_MESSAGE);
            }
            else  JOptionPane.showMessageDialog(this, "Số dư không đủ!");
        } else JOptionPane.showMessageDialog(this, "Thông tin bạn nhập không đúng!");
    }//GEN-LAST:event_btnTransferActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_btnExitActionPerformed

    private void txtNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNameMouseClicked
        // TODO add your handling code here:
        if(!check()) JOptionPane.showMessageDialog(this, "Vui lòng nhập đúng TÊN NGÂN HÀNG và SỐ TÀI KHOẢN người nhận");
        String str = cbxBankName.getSelectedItem().toString();
        if(check()){
           for(User x: a){
                if(txtCardNumber.getText().equals(x.getCardNumber())
                        && str.equals(x.getBankName()))
                      txtName.setText(x.getName());
           }
        }
    }//GEN-LAST:event_txtNameMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnTransfer;
    private javax.swing.JComboBox<String> cbxBankName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCardNumber;
    private javax.swing.JTextField txtCardNumber;
    private javax.swing.JTextField txtMoney;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
